CRITICAL - 2025-08-05 22:19:12 --> CodeIgniter\Exceptions\CriticalError: The required PHP extension "mysqli" is not loaded. Install and enable it to use "MySQLi" driver.
[Method: GET, Route: api/users]
in SYSTEMPATH/Database/Database.php on line 182.
 1 SYSTEMPATH/Database/Database.php(59): CodeIgniter\Database\Database->checkDbExtension('MySQLi')
 2 SYSTEMPATH/Database/Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(236): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(170): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\UserModel', [...])
 6 SYSTEMPATH/Common.php(801): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 SYSTEMPATH/RESTful/BaseResource.php(70): model('App\\Models\\UserModel')
 8 SYSTEMPATH/RESTful/BaseResource.php(51): CodeIgniter\RESTful\BaseResource->setModel('App\\Models\\UserModel')
 9 SYSTEMPATH/CodeIgniter.php(904): CodeIgniter\RESTful\BaseResource->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
10 SYSTEMPATH/CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
11 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-05 22:21:20 --> CodeIgniter\Exceptions\ConfigException: Invalid DBDriver name: "pdo"
[Method: GET, Route: api/users]
in SYSTEMPATH/Database/Database.php on line 172.
 1 SYSTEMPATH/Database/Database.php(59): CodeIgniter\Database\Database->checkDbExtension('pdo')
 2 SYSTEMPATH/Database/Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(236): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(170): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\UserModel', [...])
 6 SYSTEMPATH/Common.php(801): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 SYSTEMPATH/RESTful/BaseResource.php(70): model('App\\Models\\UserModel')
 8 SYSTEMPATH/RESTful/BaseResource.php(51): CodeIgniter\RESTful\BaseResource->setModel('App\\Models\\UserModel')
 9 SYSTEMPATH/CodeIgniter.php(904): CodeIgniter\RESTful\BaseResource->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
10 SYSTEMPATH/CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
11 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-05 22:22:25 --> CodeIgniter\Exceptions\ConfigException: Invalid DBDriver name: "PDO"
[Method: GET, Route: api/users]
in SYSTEMPATH/Database/Database.php on line 172.
 1 SYSTEMPATH/Database/Database.php(59): CodeIgniter\Database\Database->checkDbExtension('PDO')
 2 SYSTEMPATH/Database/Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(236): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(170): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\UserModel', [...])
 6 SYSTEMPATH/Common.php(801): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 SYSTEMPATH/RESTful/BaseResource.php(70): model('App\\Models\\UserModel')
 8 SYSTEMPATH/RESTful/BaseResource.php(51): CodeIgniter\RESTful\BaseResource->setModel('App\\Models\\UserModel')
 9 SYSTEMPATH/CodeIgniter.php(904): CodeIgniter\RESTful\BaseResource->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
10 SYSTEMPATH/CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
11 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-05 22:24:05 --> CodeIgniter\Exceptions\ConfigException: Invalid DBDriver name: "PDO"
[Method: GET, Route: api/users]
in SYSTEMPATH/Database/Database.php on line 172.
 1 SYSTEMPATH/Database/Database.php(59): CodeIgniter\Database\Database->checkDbExtension('PDO')
 2 SYSTEMPATH/Database/Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(236): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(170): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\UserModel', [...])
 6 SYSTEMPATH/Common.php(801): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 SYSTEMPATH/RESTful/BaseResource.php(70): model('App\\Models\\UserModel')
 8 SYSTEMPATH/RESTful/BaseResource.php(51): CodeIgniter\RESTful\BaseResource->setModel('App\\Models\\UserModel')
 9 SYSTEMPATH/CodeIgniter.php(904): CodeIgniter\RESTful\BaseResource->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
10 SYSTEMPATH/CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
11 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-05 22:24:51 --> CodeIgniter\Exceptions\ConfigException: Invalid DBDriver name: "pdo_mysql"
[Method: GET, Route: api/users]
in SYSTEMPATH/Database/Database.php on line 172.
 1 SYSTEMPATH/Database/Database.php(59): CodeIgniter\Database\Database->checkDbExtension('pdo_mysql')
 2 SYSTEMPATH/Database/Config.php(82): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH/Model.php(155): CodeIgniter\Database\Config::connect('default')
 4 SYSTEMPATH/Config/Factories.php(236): CodeIgniter\Model->__construct(null)
 5 SYSTEMPATH/Config/Factories.php(170): CodeIgniter\Config\Factories::createInstance('models', 'App\\Models\\UserModel', [...])
 6 SYSTEMPATH/Common.php(801): CodeIgniter\Config\Factories::__callStatic('models', [...])
 7 SYSTEMPATH/RESTful/BaseResource.php(70): model('App\\Models\\UserModel')
 8 SYSTEMPATH/RESTful/BaseResource.php(51): CodeIgniter\RESTful\BaseResource->setModel('App\\Models\\UserModel')
 9 SYSTEMPATH/CodeIgniter.php(904): CodeIgniter\RESTful\BaseResource->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
10 SYSTEMPATH/CodeIgniter.php(498): CodeIgniter\CodeIgniter->createController()
11 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-05 22:26:30 --> mysqli_sql_exception: Table 'codeigniter.users' doesn't exist in /var/www/html/system/Database/MySQLi/Connection.php:327
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 /var/www/html/system/Database/BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /var/www/html/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /var/www/html/system/Database/BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/html/system/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/html/system/BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
#6 /var/www/html/app/Controllers/Api/UserController.php(16): CodeIgniter\BaseModel->findAll()
#7 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Api\UserController->index()
#8 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\UserController))
#9 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/html/system/Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 /var/www/html/system/Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2025-08-05 22:26:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'codeigniter.users' doesn't exist
[Method: GET, Route: api/users]
in SYSTEMPATH/Database/BaseConnection.php on line 684.
 1 SYSTEMPATH/Database/BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`', [], false)
 2 SYSTEMPATH/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH/BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH/Controllers/Api/UserController.php(16): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Api\UserController->index()
 6 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\UserController))
 7 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH/Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-05 22:26:30 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'codeigniter.users' doesn't exist
in SYSTEMPATH/Database/MySQLi/Connection.php on line 332.
 1 SYSTEMPATH/Database/BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `users`')
 2 SYSTEMPATH/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `users`')
 3 SYSTEMPATH/Database/BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`', [], false)
 4 SYSTEMPATH/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH/BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH/Controllers/Api/UserController.php(16): CodeIgniter\BaseModel->findAll()
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Api\UserController->index()
 8 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\UserController))
 9 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(363): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-05 22:26:30 --> [Caused by] mysqli_sql_exception: Table 'codeigniter.users' doesn't exist
in SYSTEMPATH/Database/MySQLi/Connection.php on line 327.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(327): mysqli->query('SELECT *
FROM `users`', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `users`')
 3 SYSTEMPATH/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `users`')
 4 SYSTEMPATH/Database/BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`', [], false)
 5 SYSTEMPATH/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH/BaseModel.php(677): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH/Controllers/Api/UserController.php(16): CodeIgniter\BaseModel->findAll()
 8 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Api\UserController->index()
 9 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\UserController))
10 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-05 22:31:19 --> Error: Call to a member function lastInsertID() on true
[Method: POST, Route: api/users]
in APPPATH/Controllers/Api/UserController.php on line 40.
 1 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Api\UserController->create()
 2 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\UserController))
 3 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH/Boot.php(363): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH/Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-05 22:31:27 --> Error: Call to a member function lastInsertID() on true
[Method: POST, Route: api/users]
in APPPATH/Controllers/Api/UserController.php on line 40.
 1 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Api\UserController->create()
 2 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\UserController))
 3 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH/Boot.php(363): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH/Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-05 22:35:33 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: PUT, Route: api/users/1]
in SYSTEMPATH/BaseModel.php on line 1008.
 1 SYSTEMPATH/BaseModel.php(1008): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH/Model.php(860): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH/Controllers/Api/UserController.php(61): CodeIgniter\Model->update('1', [...])
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Api\UserController->update('1')
 5 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\UserController))
 6 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH/Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-05 22:36:38 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: PUT, Route: api/users/1]
in SYSTEMPATH/BaseModel.php on line 1008.
 1 SYSTEMPATH/BaseModel.php(1008): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH/Model.php(860): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH/Controllers/Api/UserController.php(61): CodeIgniter\Model->update('1', [...])
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Api\UserController->update('1')
 5 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\UserController))
 6 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH/Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-05 22:37:25 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: PUT, Route: api/users/1]
in SYSTEMPATH/BaseModel.php on line 1008.
 1 SYSTEMPATH/BaseModel.php(1008): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH/Model.php(860): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH/Controllers/Api/UserController.php(61): CodeIgniter\Model->update('1', [...])
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Api\UserController->update('1')
 5 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Api\UserController))
 6 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH/Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
